version: 2

sources:
  - name: agri_raw
    description: >
      Données brutes agricoles provenant de sources institutionnelles
      (World Bank, FAO, IFPRI/ASTI). Aucune transformation métier appliquée.
    database: spherical-booth-474518-n6
    schema: agri_raw
    tables:
      - name: worldbank_agri_employment
        description: >
          Indicateur World Bank : part de l’emploi agricole par pays et par année.
      - name: fao_agri_production
        description: >
          Données FAOSTAT : production agricole (quantité produite) par pays et année.
      - name: asti_rd_exp
        description: >
          Dépenses de R&D agricole (ASTI – IFPRI), indicateur institutionnel.

models:
  - name: stg_worldbank_agri_employment
    description: >
      Staging World Bank.
      Normalise les colonnes, applique le typage et fixe le grain (pays, année).
    columns:
      - name: country_code
        description: Code pays ISO3.
        tests:
          - not_null
      - name: year
        description: Année calendaire.
        tests:
          - not_null
      - name: agri_employment_pct
        description: Part de l’emploi agricole (% de l’emploi total).
    tests:
      - unique_combination:
          arguments:
            combination_of_columns:
              - country_code
              - year

  - name: stg_fao_agri_production
    description: >
      Staging FAO.
      Normalise les colonnes, applique le typage et fixe le grain (pays, année).
    columns:
      - name: country_code
        description: Code pays ISO3.
        tests:
          - not_null
      - name: year
        description: Année calendaire.
        tests:
          - not_null
    tests:
      - unique_combination:
          arguments:
            combination_of_columns:
              - country_code
              - year

  - name: stg_asti_rd_exp
    description: >
      Staging ASTI.
      Normalise les colonnes, applique le typage et fixe le grain (pays, année).
    columns:
      - name: country_code
        description: Code pays ISO3.
        tests: [not_null]
      - name: year
        description: Année calendaire.
        tests: [not_null]
      - name: agri_rd_exp_total
        description: Dépenses de R&D agricole.
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: ["country_code", "year"]
